Platform/ARM/Drivers/BootMonFs: remove unused ImageCount variable
ImageCount doesn't use for anything in initialisation.
Therefore, remove ImageCount variable otherwise it faces
below build error with CLANGDWARF:

  edk2-platforms/Platform/ARM/Drivers/BootMonFs/BootMonFsImages.c:191:28: error: variable 'ImageCount' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>
(cherry picked from commit f44dbcdf07c775a06237a5cde8e8e8ab0340f9cb)