Ampere/AmpereAltraPkg: fix warnings about uninitialized variable
(cherry picked from commit c1bcfefa4862aa637f733e13d54d6b914111a35b)

This patch fixes the following warnings:

RootComplexConfigDxe/RootComplexConfigDxe.c: In function 'RouteConfig':
RootComplexConfigDxe/RootComplexConfigDxe.c:341:12: error: 'VarStoreConfig'
  may be used uninitialized in this function [-Werror=maybe-uninitialized]
   Status = HiiConfigRouting->ConfigToBlock (
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                HiiConfigRouting,
                                ~~~~~~~~~~~~~~~~~
                                Configuration,
                                ~~~~~~~~~~~~~~
                                (UINT8 *)VarStoreConfig,
                                ~~~~~~~~~~~~~~~~~~~~~~~~
                                &BufferSize,
                                ~~~~~~~~~~~~
                                Progress
                                ~~~~~~~~
                                );
                                ~
SystemFirmwareUpdateDxe/SystemFirmwareUpdateDxe.c:
  In function 'SystemFirmwareUpdateSetVariable':
SystemFirmwareUpdateDxe/SystemFirmwareUpdateDxe.c:269:25:
  error: 'SubId' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]

   mUpdateFWSubId        = SubId;
   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

cc1: all warnings being treated as errors

Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
(cherry picked from commit c1bcfefa4862aa637f733e13d54d6b914111a35b)

Change-Id: I81d2d7e620e8989a33408ca9140eb1de71de6a61