Platform/ARM/ArmShellCmdRunAxf: Fix build with clang
(cherry picked from commit 5806fa55ed4288e6e7fbb8fe7f7399b4a75cd591)

Clang build fails with the below warning:
  |  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:216:11: error: variable
  |    'FileSize' is used uninitialized whenever 'if' condition is false
  |    [-Werror,-Wsometimes-uninitialized].
  |                if (FileHandle != NULL) {
  |                    ^~~~~~~~~~~~~~~~~~
  |  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:281:38: note:
  |    uninitialized use occurs here.
  |            WriteBackDataCacheRange (FileData, FileSize);
  |                                               ^~~~~~~~
  |  Platform/ARM/Library/ArmShellCmdRunAxf/RunAxf.c:136:39: note: initialize
  |    the variable 'FileSize' to silence this warning
  |            UINTN                       FileSize;
  |                                                ^
  |                                                 = 0
  |  4 errors generated.

Fix it by initializing the variable.

Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
(cherry picked from commit 5806fa55ed4288e6e7fbb8fe7f7399b4a75cd591)

Change-Id: I6d8826eb60c1844e01bf58780939fecbd4d28205