IpmiFeaturePkg/GenericIpmi: add IpmiFeaturePkg.dec to packages list
(cherry picked from commit 223bed94a1b619b9fcd20550657ec8f99aa72c07)

GCC is unable to find a header file located into IpmiFeaturePkg:
  fatal error: Library/ServerMgmtRtLib.h: No such file or directory
     11 | #include <Library/ServerMgmtRtLib.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
Reviewed-by: Nate DeSimone <nathaniel.l.desimone@intel.com>
Cc: Liming Gao <gaoliming@byosoft.com.cn>
(cherry picked from commit 223bed94a1b619b9fcd20550657ec8f99aa72c07)

Change-Id: I2d04e35c92a41310588ab24c2c49d08f2fdbe793