multiple Arm platforms: set WritePolicyValid for all cache types
(cherry picked from commit 10e2eb030de3fa96433009465aab6eff0f199117)

acpiview complains:

ERROR: On Arm based systems, all cache properties must be provided in
the cache type structure. Missing 'Write Policy Valid' flag.

ACPI specification says:

> Set to 1 if the write policy attribute described is valid. A value
> of 0 indicates that, where possible, processor architecture specific
> discovery mechanisms should be used to ascertain the value of this
> attribute.

Signed-off-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>
Reviewed-by: Leif Lindholm <quic_llindhol@quicinc.com>
(cherry picked from commit 10e2eb030de3fa96433009465aab6eff0f199117)

Change-Id: Iddd34d2d3e45f20348386fc934bda08dbccc566e

SyncScript: UpstreamBase is 10e2eb030de3fa96433009465aab6eff0f199117