IpmiFeaturePkg/GenericIpmi: add EFIAPI for driver entrypoints
(cherry picked from commit e70b3334ca0778150fcd6ad24e0fbbd1e32a7d3b)

Fix gcc build failure:
IpmiFeaturePkg/GenericIpmi/Smm/SmmGenericIpmi.c:414:1:
  error: conflicting types for 'InitializeSmmGenericIpmi'
  414 | InitializeSmmGenericIpmi (
      | ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from <command-line>:
IpmiFeaturePkg/GenericIpmi/Smm/SmmGenericIpmi/DEBUG/AutoGen.h:138:1:
  note: previous declaration of 'InitializeSmmGenericIpmi' was here
  138 | InitializeSmmGenericIpmi (
      | ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
Reviewed-by: Nate DeSimone <nathaniel.l.desimone@intel.com>
Cc: Liming Gao <gaoliming@byosoft.com.cn>
(cherry picked from commit e70b3334ca0778150fcd6ad24e0fbbd1e32a7d3b)

Change-Id: I2cae95c00243e404c01aa5950ddd1e483dc39c9a