Platform/ARM/Drivers/NorFlashDxe: fix build failure with CLANGDWARF
When FVP platform is built with CLANGDWARF toolchain,
below build error splat happens:

  edk2-platforms/Platform/ARM/Drivers/NorFlashDxe/NorFlashStandaloneMm.c:398:14:
  error: variable 'ProtocolGuid' is used uninitialized whenever 'if' condition is

Fix this build failure.

Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>
(cherry picked from commit 28fabd83cc21ecf6d80ffb58fc21c75b32bc0db2)