Ampere/JadePkg: fix warnings about uninitialized variable
(cherry picked from commit 23037cf80b21f63cd6107be369f419155928a6a2)

This patch fixes a bunch of warnings similar to:
Ampere/JadePkg/Drivers/SmbiosPlatformDxe/SmbiosPlatformDxe.c:446:15:
  error: 'Status' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]

   EFI_STATUS  Status;
               ^~~~~~
cc1: all warnings being treated as errors

And a single warning about MemorySize variable:
SmbiosPlatformDxe/Type19/PlatformMemoryArrayMappedAddressFunction.c:131:12:
  error: 'MemorySize' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]

         if (MemorySize != 0) {
            ^
cc1: all warnings being treated as errors

Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
(cherry picked from commit 23037cf80b21f63cd6107be369f419155928a6a2)

Change-Id: I1444f062983efe3250c6f5e924991aa11ffa6ae2