IntelSiliconPkg: Cast UINT32 to UINT8 conversion in ReportCpuHobLib
(cherry picked from commit e89f5830bdd19c73a99d745b2646f4821069fc76)

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3404

Commit d3c10d3 introduced a build error in ReportCpuHobLib.c:

IntelSiliconPkg\Library\ReportCpuHobLib\ReportCpuHobLib.c(30):
  error C2220: warning treated as error - no 'object' file generated
IntelSiliconPkg\Library\ReportCpuHobLib\ReportCpuHobLib.c(30):
  warning C4244: '=': conversion from 'UINT32' to 'UINT8',
  possible loss of data

This commit explicitly cast the assignment to fix the build error.

Reviewed-by: Ray Ni <ray.ni@intel.com>
Cc: Rangasai V Chaganty <rangasai.v.chaganty@intel.com>
Cc: SofiaX Chuang <sofiax.chuang@intel.com>
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
(cherry picked from commit e89f5830bdd19c73a99d745b2646f4821069fc76)

Change-Id: Id9907b7083a1dd5b636ac981939a0de0b17fa60d

SyncScript: UpstreamBase is e89f5830bdd19c73a99d745b2646f4821069fc76